# FAT16 constants
BYTES_PER_SECTOR_OFFSET = 11
SECTORS_PER_CLUSTER_OFFSET = 13
RESERVED_SECTORS_OFFSET = 14
NUMBER_OF_FATS_OFFSET = 16
ROOT_DIR_ENTRIES_OFFSET = 17
SECTORS_PER_FAT_OFFSET = 22

DIR_ENTRY_SIZE = 32
FILE_NAME_SIZE = 8
FILE_EXT_SIZE = 3

# File attributes
READ_ONLY = 0x01
HIDDEN = 0x02
SYSTEM = 0x04
VOLUME_LABEL = 0x08
DIRECTORY = 0x10
ARCHIVE = 0x20

# Special markers
ENTRY_FREE = 0x00
ENTRY_DELETED = 0xE5
END_OF_CLUSTER = 0xFFFF